config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations"}

  
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'forgot_password'
      put 'forgot_password_send_otp'
      put 'forgot_password_process_otp'
      get 'forgot_password_enter_otp/:mobile' => 'users#forgot_password_enter_otp', as: 'forgot_password_enter_otp'
      get 'mass_signup' => 'users#mass_signup', as: 'mass_signup'
      post 'mass_create' => 'users#mass_create', as: 'mass_create'

    end
  end


  resources :conversations
  resources :messages
  resources :projects, only: [:index]
  resources :groups
  resources :requests
  resources :notifications, only: [:index]
  

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all




  root 'welcome#index'

  get 'home' => 'ui#index'

  post 'incoming' => 'api#receive'

  get 'projects/:id/edit' => 'projects#edit', as: 'edit_project'
  get 'projects/:id/list_of_users' => 'projects#list_of_users', as: 'all_participants'
  get 'projects/new' => 'projects#new', as: 'new_project'
  post 'projects' => 'projects#create'

  get 'welcome/home' => 'welcome#home', as: 'welcome'
  get 'groups/home' => 'groups#index'
  get 'groups/new' => 'groups#new'
  get 'groups/:id/list_of_users' => 'groups#list_of_users', as: 'all_members'
  get 'groups/:id/associated_projects' => 'groups#associated_projects', as: 'associated_projects'
  put 'projects/:id/join' => 'projects#join', as: 'join'
  put 'projects/:id/leave' => 'projects#leave', as: 'leave'
  get 'projects/:id/conversations/new' => 'conversations#new', as: 'new_convo'
  post 'projects/:id/conversations/' => 'conversations#create', as: 'create_new_convo'
  get  'projects/:id/conversations/:id' => 'conversations#show', as: 'view_convo'
  get  'projects/:id/conversations/:id/pick_users' => 'conversations#pick_users', as: 'pick_convo_users'
  put  'projects/:id/conversations/:id/add_users/' => 'conversations#add_users', as: 'add_convo_users'

  get  'projects/:id/pick_users' => 'projects#pick_users', as: 'pick_project_users'
  put  'projects/:id/add_users/' => 'projects#add_users', as: 'add_project_users'

  get 'projects/:id/dashboard' => 'projects#dashboard'
  get 'dashboard/messages' => 'dashboard#messages'
  get 'dashboard/equity' => 'dashboard#equity'
  get 'dashboard/cloud' => 'dashboard#cloud'

  post 'messages/create' => 'messages#create', as: 'post_new_message'
  get 'projects/:project_id/show' => 'projects#show', as: 'project'
  patch 'projects/:id' => 'projects#update', as: 'update_project'


  get 'users/:id/manage' => 'users#manage', as: 'manage_user'
  get 'users/:id/delete_account' => 'users#delete_account', as: 'delete_account'
  patch 'users/:id/delete_user' => 'users#delete_user', as: 'delete_user'
  


  get 'projects/:id/manage' => 'projects#manage_participants', as: 'manage_project'
  get 'projects/:id/remove_participants' => 'projects#remove_participants', as: 'remove_project_participants'
  put 'projects/:id/remove' => 'projects#remove_participant', as: 'remove_project_participant'
  get 'projects/:id/transfer_leadership' => 'projects#transfer_leadership', as: 'transfer_project_leadership'
  post 'projects/:id/new_leader' => 'projects#new_leader', as: 'new_leader'

  put 'requests/:id/approve' => 'requests#approve', as: 'approve_request'
  put 'requests/:id/decline' => 'requests#decline', as: 'decline_request'
  put 'requests/:id/cancel_request' => 'requests#cancel_request', as: 'cancel_request'
  
  get 'projects/:id/add_affiliations' => 'projects#add_affiliations', as: 'add_affiliations'
  put 'projects/:id/affiliate' => 'projects#affiliate', as: 'affiliate'

  put 'users/:id/add_contact' => 'users#add_colleague', as: 'add_contact'
  put 'users/:id/remove_contact' => 'users#remove_colleague', as: 'remove_contact'
  

  put 'groups/:id/join' => 'groups#join', as: 'join_group'
  put 'groups/:id/leave' => 'groups#leave', as: 'leave_group'

  get 'groups/:id/manage' => 'groups#manage_members', as: 'manage_group'

  get  'groups/:id/pick_members' => 'groups#pick_members', as: 'pick_group_members'
  put  'groups/:id/add_members/' => 'groups#add_members', as: 'add_group_members'
  get 'groups/:id/remove_members' => 'groups#remove_members', as: 'remove_group_members'
  put 'groups/:id/remove_member' => 'groups#remove_member', as: 'remove_group_member'
  get 'groups/:id/transfer_leadership' => 'groups#transfer_leadership', as: 'transfer_group_leadership'
  post 'groups/:id/new_leader' => 'groups#new_leader', as: 'new_group_leader'

  get 'conversations/:id/posts/new' => 'posts#create', as: 'new_post'
  post 'conversations/:id/posts' => 'posts#create', as: 'create_post'

  get 'projects/:id/change_plan' => 'projects#change_plan', as: 'change_project_plan'
  

  get 'search' => 'search#index', :as => 'search'
  get 'search/contacts' => 'search#contacts', :as => 'contacts_results'
  get 'search/projects' => 'search#projects', :as => 'projects_results'
  get 'search/groups' => 'search#groups', :as => 'groups_results'


  put 'admin/:id/change_user_status' => 'admin#change_user_status', :as => 'update_user_status' 
  put 'admin/:id/change_project_status' => 'admin#change_project_status', :as => 'update_project_status' 
  put 'admin/:id/change_group_status' => 'admin#change_group_status', :as => 'update_group_status' 

  get 'welcome/contact_us' => 'welcome#contact_us', :as => 'contact_us'
  get 'welcome/about_us' => 'welcome#about_us', :as => 'about_us'
  get 'welcome/plan' => 'welcome#plan', :as => 'plan'
  post 'welcome/send_authentication_code' => 'welcome#send_authentication_code', :as => 'send_authentication_code'
  post 'welcome/authenticate_code' => 'welcome#authenticate_code', :as => 'authenticate_code'
  
  put 'notifications/mark_as_read' => 'notifications#mark_as_read', :as => 'mark_as_read'
  put 'notifications/mark_all_as_read' => 'notifications#mark_all_as_read', :as => 'mark_all_as_read'
  


  resources :passwords do
    collection do
      put 'change_password', as: :change
    end
  end









end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	has_and_belongs_to_many :users, join_table: "conversers"
	belongs_to :project
	has_many :messages
  delegate :code, :name, :to => :project, :prefix => true


  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  after_create :assign_tag

  def assign_tag
    tags = %w(red green blue yellow purple teal orange pink grey maroon violet turquoise salmon plum orchid olive magenta lime indigo gold fuchsia cyan azure lavender silver) - project.conversations.map(&:code)
    if tags.size == 0
      update(:code => '000')
    elsif project.conversations.size == 1
      update(:code => 'all')
    else
      update(:code => tags.sample)
    end
  end

  private
    def slug_candidates
      project = self.project.slug
      [
        :name,
        [:name, :code],
        [:name, :code, :project]
      ]
    end


end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
	def show
		@conversation = Conversation.friendly.find(params[:id])
		@conversers = @conversation.users
		@message = Message.new
		@messages = @conversation.messages
		@project = @conversation.project
	end

	def new
		@project = Project.friendly.find(params[:id])
		#@users = @project.users.collect {|p| [ p.name, p.id ] }
		@conversation = Conversation.new
	end

	def create
		@project = Project.friendly.find(params[:id])
		@conversation = Conversation.create(conversation_params.merge(:project_id => @project.id))
		@users = @project.users
		@conversation.users << current_user
		#redirect_to view_convo_path(@project, @conversation)
		redirect_to pick_convo_users_path(@conversation)
	end

	def pick_users
		#@project = Project.find(params[:id])
		@conversation = Conversation.friendly.find(params[:id])
		@project = @conversation.project
		existent_users = @conversation.users
		@users = @project.users - existent_users
	end

	def add_users
		#@project = Project.find(params[:project_id])
		@conversation = Conversation.includes(:project).friendly.find(params[:conversation_id])
		@user = User.friendly.find(params[:user_id])
		@conversation.users << @user
		add_users_notification_to_user(@conversation, @user)
		redirect_to :back, notice: "#{@user.name} was successfully added to #{@conversation.name}"
	end


	private

	def conversation_params
		params.require(:conversation).permit(:name)
	end

  def add_users_notification_to_user(conversation, user)
  	message = "You have been added to conversation named #{conversation.name} in named <a href=#{project_path(conversation.project)}>#{conversation.project_name}</a>."
    Notification.send_notification(user, 'Added to Conversation', message)
  end


end

app/views/conversations/_conversation.html.slim
/!
  .row
    .col-sm-6
      b = "\##{conversation.code}:#{conversation.name}"
    .col-sm-6
      = link_to "Edit/Add People", view_convo_path(conversation)
  br
  =conversation.users.map{|user| user.name}.join(', ')
  br
  = "Total Messages: "
  =conversation.messages.count
  table.inbox[border="1" width="80%"]
    - conversation.messages.each do |message|
      tr
        td
          =link_to message.sender.name, user_path(message.sender)
          | : 
          =message.body
          br
          =message.sent
          br
    tr
      td
        - if can? :leave, conversation.project
          = render partial: 'messages/new'




          
.row.m-5-percentage 
  .col-xs-9.col-sm-9.m-t-20
    .conversation-name.no-wrap
      = "#{conversation.name}"
    .conversation-members.no-wrap
      span.glyphicon.glyphicon-user.grey-color
      = " #{conversation.users.map(&:first_name).join(',').truncate(40)}"
  .col-xs-3.col-sm-3.m-t-20
    - if @conversation != conversation
      .pull-right
        /! = "Edit" 
        = link_to "Edit", view_convo_path(conversation)
        div.m-5  
        =button_to "...", view_convo_path(conversation), :class => 'button tag-btn', :method => 'get'

.row.m-0
  .col-xs-11.col-sm-11.p-0
    input.form-control placeholder="Search" type="text" class="search-box project-search-box" 
  .col-xs-1.col-sm-1.p-l-0
    button.btn.btn-default.project-search-button.m-l-minus-7 type="submit" 
      span.glyphicon.glyphicon-search.project-search-glyphicon


.row
  .messages-list
    - colors = ['#cac8d6', '#d9eaf1']

    - @messages.each_with_index do |message, index|
      - random_color = colors[index%2]

      .chat-box-right style="background-color: #{random_color}"
        .row
          .col-sm-10
            = message.body
          .col-sm-2
            .row
              = "#{time_ago_in_words(message.created_at)} ago"
            .row
              - read_user_names = other_users(message, @conversation_users).have_read(message).map(&:first_name).join("\n")
              /!
                p title=read_user_names.html_safe
                  | See who read
              a href="#" data-toggle="tooltip" title=read_user_names data-content=read_user_names.html_safe id='message-read-by' data-placement="bottom"
                | Message read by
      .sender
        - if message.sender == current_user
          = "You"
        - else
          = message.sender_first_name
      
  .send.message-send
    - if can? :leave, conversation.project
      = render partial: 'messages/new'

app/views/conversations/new.html.slim
/!
	| New Conversation 
	= form_for @conversation, :url => create_new_convo_path(@project) do |f|
	  = f.label "Conversation name:"
	  = f.text_field :name
	  br
	  =f.submit


div.new-group-page
  .row
    .col-md-3
    .col-md-6
      .form-elements.text-center
        h2 New Conversation
        = form_for @conversation, :url => create_new_convo_path(@project) do |f|
          = f.text_field :name, placeholder: "Conversation Name", class: "form-control m-t-50", required: true   
          button.button-format.m-t-30  Submit

app/views/conversations/pick_users.html.slim
/!
	| Add Users
	br
	- @users.each do |user|
	  =user.name
	  =button_to "Add", add_convo_users_path(:project_id => @project, :conversation_id =>@conversation, :user_id => user), :method => 'put'
	  br
	=button_to "Done", project_path(:project_id => @project, :conversation_id => @conversation), :method => 'get'





div.edit-profile-page
  .row
    .col-md-3
    .col-md-offset-1.col-md-4
      .form-elements
        h2
        	= "Add Users"
        h5 
        	| Add users to 
        	b 
        		| #{@conversation.name}
    	br
        .m-b-20
        - if @users.empty?
          i
            | There are no more users in this project to add to your conversation at this time.
        - else
          - @users.each do |user|
            .row.m-b-10
              .col-sm-5
                =link_to user.name, user_path(user)
              .col-sm-6
                =button_to "Add", add_convo_users_path(:project_id => @project, :conversation_id =>@conversation, :user_id => user), :method => 'put', :class => 'transfer-leadership-button'
            br

    .col-md-4.text-right.m-t-20
        = link_to 'Back', conversation_path(@conversation)

app/views/conversations/show.html.slim
/!
	| Key Screen 3 - Main Message Page aka Converation Page 
	=link_to @project.name, project_path(:project_id =>@project, :conversation_id => @project.conversations.first)
	br
	= "\##{@conversation.code}:#{@conversation.name}"
	br
	- @conversers.each do |c|
	  =c.name
	br
	- if can? :add_users, @conversation
	  =button_to "Add Users", pick_convo_users_path(@conversation), :method => 'get'
	  br
	|  Messages: 
	- @messages.each do |message|
	  =message.sender.name
	  | : 
	  = message.body
	= render partial: "messages/new"


- @current_convo = @conversation

div.group-details-block.conversation-show-block-xs
  .row
  	h2
  		b.no-wrap
  			= link_to @conversation.project_name.capitalize, project_path(@conversation.project)
    .col-md-7.col-sm-12.col-xs-12.p-0
      .conversation-detail
        = render partial: 'conversations/conversation', object: @current_convo

    .col-xs-offset-1.col-md-4.col-sm-12.col-xs-12.p-r-0
      .row
        .col-md-offset.col-md-4.col-sm-4.col-xs-4 
          h3.text-muted.project-members-header  Members
        .col-md-offset-2.col-md-4.col-sm-8.col-xs-8
          .col-sm-6.col-md-12.col-xs-6
            =button_to "Add +", pick_convo_users_path(@conversation), :method => 'get', :class => 'add-button'
      .col-md-12.p-r-0
        .row
          .col-md-12
            hr.project-member-border

        .row.m-t-minus-30
          - @conversers.each do |converser|
            .participants-list.col-xs-12.col-sm-6.col-md-12.m-t-30.m-0.p-0
              .col-xs-3.col-sm-3.col-md-4.p-0
                .div-rounded
              .col-xs-9.col-sm-9.col-md-8.p-l-10-percentage
                h4.project-members-name
                  b.no-wrap
                    = link_to converser.name, user_path(converser)
                h4.heading-styles.silver-color  
                  = converser.location

