config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations"}

  
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'forgot_password'
      put 'forgot_password_send_otp'
      put 'forgot_password_process_otp'
      get 'forgot_password_enter_otp/:mobile' => 'users#forgot_password_enter_otp', as: 'forgot_password_enter_otp'
      get 'mass_signup' => 'users#mass_signup', as: 'mass_signup'
      post 'mass_create' => 'users#mass_create', as: 'mass_create'

    end
  end


  resources :conversations
  resources :messages
  resources :projects, only: [:index]
  resources :groups
  resources :requests
  resources :notifications, only: [:index]
  

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all




  root 'welcome#index'

  get 'home' => 'ui#index'

  post 'incoming' => 'api#receive'

  get 'projects/:id/edit' => 'projects#edit', as: 'edit_project'
  get 'projects/:id/list_of_users' => 'projects#list_of_users', as: 'all_participants'
  get 'projects/new' => 'projects#new', as: 'new_project'
  post 'projects' => 'projects#create'

  get 'welcome/home' => 'welcome#home', as: 'welcome'
  get 'groups/home' => 'groups#index'
  get 'groups/new' => 'groups#new'
  get 'groups/:id/list_of_users' => 'groups#list_of_users', as: 'all_members'
  get 'groups/:id/associated_projects' => 'groups#associated_projects', as: 'associated_projects'
  put 'projects/:id/join' => 'projects#join', as: 'join'
  put 'projects/:id/leave' => 'projects#leave', as: 'leave'
  get 'projects/:id/conversations/new' => 'conversations#new', as: 'new_convo'
  post 'projects/:id/conversations/' => 'conversations#create', as: 'create_new_convo'
  get  'projects/:id/conversations/:id' => 'conversations#show', as: 'view_convo'
  get  'projects/:id/conversations/:id/pick_users' => 'conversations#pick_users', as: 'pick_convo_users'
  put  'projects/:id/conversations/:id/add_users/' => 'conversations#add_users', as: 'add_convo_users'

  get  'projects/:id/pick_users' => 'projects#pick_users', as: 'pick_project_users'
  put  'projects/:id/add_users/' => 'projects#add_users', as: 'add_project_users'

  get 'projects/:id/dashboard' => 'projects#dashboard'
  get 'dashboard/messages' => 'dashboard#messages'
  get 'dashboard/equity' => 'dashboard#equity'
  get 'dashboard/cloud' => 'dashboard#cloud'

  post 'messages/create' => 'messages#create', as: 'post_new_message'
  get 'projects/:project_id/show' => 'projects#show', as: 'project'
  patch 'projects/:id' => 'projects#update', as: 'update_project'


  get 'users/:id/manage' => 'users#manage', as: 'manage_user'
  get 'users/:id/delete_account' => 'users#delete_account', as: 'delete_account'
  patch 'users/:id/delete_user' => 'users#delete_user', as: 'delete_user'
  


  get 'projects/:id/manage' => 'projects#manage_participants', as: 'manage_project'
  get 'projects/:id/remove_participants' => 'projects#remove_participants', as: 'remove_project_participants'
  put 'projects/:id/remove' => 'projects#remove_participant', as: 'remove_project_participant'
  get 'projects/:id/transfer_leadership' => 'projects#transfer_leadership', as: 'transfer_project_leadership'
  post 'projects/:id/new_leader' => 'projects#new_leader', as: 'new_leader'

  put 'requests/:id/approve' => 'requests#approve', as: 'approve_request'
  put 'requests/:id/decline' => 'requests#decline', as: 'decline_request'
  put 'requests/:id/cancel_request' => 'requests#cancel_request', as: 'cancel_request'
  
  get 'projects/:id/add_affiliations' => 'projects#add_affiliations', as: 'add_affiliations'
  put 'projects/:id/affiliate' => 'projects#affiliate', as: 'affiliate'

  put 'users/:id/add_contact' => 'users#add_colleague', as: 'add_contact'
  put 'users/:id/remove_contact' => 'users#remove_colleague', as: 'remove_contact'
  

  put 'groups/:id/join' => 'groups#join', as: 'join_group'
  put 'groups/:id/leave' => 'groups#leave', as: 'leave_group'

  get 'groups/:id/manage' => 'groups#manage_members', as: 'manage_group'

  get  'groups/:id/pick_members' => 'groups#pick_members', as: 'pick_group_members'
  put  'groups/:id/add_members/' => 'groups#add_members', as: 'add_group_members'
  get 'groups/:id/remove_members' => 'groups#remove_members', as: 'remove_group_members'
  put 'groups/:id/remove_member' => 'groups#remove_member', as: 'remove_group_member'
  get 'groups/:id/transfer_leadership' => 'groups#transfer_leadership', as: 'transfer_group_leadership'
  post 'groups/:id/new_leader' => 'groups#new_leader', as: 'new_group_leader'

  get 'conversations/:id/posts/new' => 'posts#create', as: 'new_post'
  post 'conversations/:id/posts' => 'posts#create', as: 'create_post'

  get 'projects/:id/change_plan' => 'projects#change_plan', as: 'change_project_plan'
  

  get 'search' => 'search#index', :as => 'search'
  get 'search/contacts' => 'search#contacts', :as => 'contacts_results'
  get 'search/projects' => 'search#projects', :as => 'projects_results'
  get 'search/groups' => 'search#groups', :as => 'groups_results'


  put 'admin/:id/change_user_status' => 'admin#change_user_status', :as => 'update_user_status' 
  put 'admin/:id/change_project_status' => 'admin#change_project_status', :as => 'update_project_status' 
  put 'admin/:id/change_group_status' => 'admin#change_group_status', :as => 'update_group_status' 

  get 'welcome/contact_us' => 'welcome#contact_us', :as => 'contact_us'
  get 'welcome/about_us' => 'welcome#about_us', :as => 'about_us'
  get 'welcome/plan' => 'welcome#plan', :as => 'plan'
  post 'welcome/send_authentication_code' => 'welcome#send_authentication_code', :as => 'send_authentication_code'
  post 'welcome/authenticate_code' => 'welcome#authenticate_code', :as => 'authenticate_code'
  
  put 'notifications/mark_as_read' => 'notifications#mark_as_read', :as => 'mark_as_read'
  put 'notifications/mark_all_as_read' => 'notifications#mark_all_as_read', :as => 'mark_all_as_read'
  


  resources :passwords do
    collection do
      put 'change_password', as: :change
    end
  end









end

app/models/group.rb
class Group < ActiveRecord::Base
    belongs_to :group_leader, :class_name => "User"
    #has_many :users, through: :organizations
    has_and_belongs_to_many :users, join_table: "members"
    has_many :requests
    has_many :lead_groups
    has_many :join_groups
    has_one :new_group
    has_and_belongs_to_many :projects, join_table: "affiliations"
    has_many :posts
    validates_uniqueness_of :name, :message => "Sorry, this group name has already been taken"
    paginates_per 6

    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

    extend FriendlyId
    friendly_id :slug_candidates, use: :slugged

    delegate :name, :email, :mobile, :to => :group_leader, :prefix => true


    after_create :send_request_to_admin

    scope :active, -> { where(:is_active => true) }





  	def self.search(search)
  		return where("name LIKE ?", "%#{search}%") - where(:privacy => "private")
  		#where("content LIKE ?", "%#{search}%")
	  end

    private

    def send_request_to_admin
      NewGroup.create(:group_id => self.id, :request_by => self.group_leader_id, :request_to => Admin.first.id,
       :pending => true)
    end

    def slug_candidates
      [
        :name,
        [:name, :location]
      ]
    end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :check_group_leader, except: [:index, :show, :new, :create, :join, :leave]
  before_action :authenticate_user!

  def new
    @group = Group.new
  end

  def index
    # @groups = current_user.groups.includes(:group_leader, :projects)
    @groups = current_user.groups.includes(:group_leader, :projects).order(:name).page params[:page]
  end

  def create
    @group = Group.create(group_params.merge(:group_leader_id => current_user.id))
    @group.users << current_user
    #redirect_to group_path(@group)
    if @group.save
      group_create_notifications(@group)
      redirect_to group_path(@group), notice: "#{@group.name} was successfully created"
    else
      flash.now[:alert] = "Sorry, that group name is already taken"
      render new_group_path(@group), alert: "Sorry that group name is already taken"
    end
  end

  def edit
    @group = Group.friendly.find(params[:id])
  end

  def update
    @group = Group.friendly.find(params[:id])
    @group.update_attributes(group_params)
    redirect_to manage_group_path(@group), notice: "#{@group.name} has been updated"
  end

  def show
    @group = Group.includes(:projects, :users, :posts).friendly.find(params[:id])
    @members = @group.users.limit(4)
    @projects = @group.projects.limit(4)
    @posts = @group.posts
    @requests_sent_by_user = JoinGroup.requests_sent_by_user(current_user.id, @group.id)
    @join_request_sent = !@requests_sent_by_user.blank?
    @post = Post.new
  end

  def destroy
    @group = Group.friendly.find(params[:id])
    if @group.destroy
      redirect_to 'index', notice: "Left group"
    else
      render :new, notice: "Still in group"
    end
  end

  def list_of_users
    @group = Group.includes(:users).friendly.find(params[:id])
    @users = @group.users
    @user_count = @users.size
  end

  def associated_projects
    @group = Group.includes(:projects).friendly.find(params[:id])
    @projects = @group.projects
    @project_count = @projects.size
  end

  def join
    @group = Group.friendly.find(params[:id])
    # @project.users << current_user
    @request = Request.create(:group_id => @group.id, :user_id => current_user.id,
      :request_by => current_user.id, :request_to => @group.group_leader_id, :pending => true, :type => 'JoinGroup')

    if @request.save!
       group_join_request_notifications(@group)
    end

    redirect_to :back, notice: "Your request to join #{@group.name} has been sent"
  end

  def leave
    @group = Group.friendly.find(params[:id])
    @group.users.delete(current_user)
    leave_notification(@group, current_user)
    redirect_to :back, notice: "You have left #{@group.name}"
  end

  def manage_members
    @group = Group.friendly.find(params[:id])
    @members = @group.users
    @requests = JoinGroup.includes(:user).where(:group_id => @group.id, :pending => true)
  end

  def pick_members
    @group = Group.friendly.find(params[:id])
    all_users = User.all
    existent_users = @group.users
    @users = all_users - existent_users
  end

  def add_members
    @group = Group.friendly.find(params[:group_id])
    @user = User.friendly.find(params[:user_id])
    @group.users << @user
    add_members_notification_to_user(@group, @user)
    redirect_to :back,  notice: "#{@user.name} was successfully added to #{@group.name}"
  end

  def remove_members
    @group = Group.friendly.find(params[:id])
    @members = @group.users - [@group.group_leader]
  end

  def remove_member
    @group = Group.friendly.find(params[:group_id])
    @user = User.friendly.find(params[:user_id])
    @group.users.delete(@user)
    remove_members_notification_to_user(@group, @user)

    redirect_to :back, notice: "#{@user.name} was successfully removed from #{@group.name}"
  end

  def transfer_leadership
    @group = Group.friendly.find(params[:id])
    @members = @group.users - [current_user]
  end

  def new_leader
    @group = Group.friendly.find(params[:group_id])
    @user = User.friendly.find(params[:user_id])
    @request = Request.create(:group_id => @group.id, :user_id => @user.id, :request_to => @user.id,
     :request_by => @group.group_leader_id, :pending => true, :type => 'LeadGroup')

    group_new_leader_notifications(@group, @user)

    #@project.update_attributes(:project_manager_id => @user.id)
    redirect_to group_path(@group), notice: "leadership of #{@group.name} will be transfered to #{@user.name} upon approval"
  end

  private

  def check_group_leader
    group = Group.friendly.find(params[:id])
    if current_user.managed_groups.include? group
      true
    else
      redirect_to group_path(group), notice: "Sorry, you cannot access this path."
    end
  end

  def group_params
    params.require(:group).permit(:name, :location, :privacy, :scale, :avatar)
  end

  def group_join_request_notifications(group)
    message_to_group_leader = "<a href=#{user_path(current_user)}>#{current_user.name.capitalize}</a> has requested
      to join the group <a href=#{group_path(group)}>#{group.name}</a>. Please go to this
       <a href=#{requests_path}>link</a> to approve it."
    message_to_user = "Your request has been successfully placed to join the
       group <a href=#{group_path(group)}>#{group.name}</a>."

    Notification.send_notification(group.group_leader, 'Join Group', message_to_group_leader)
    Notification.send_notification(current_user, 'Join Group', message_to_user)
  end


  def group_create_notifications(group)
    message_to_group_leader = "You have successfully created a new group named
       <a href=#{group_path(group)}>#{group.name}</a>."
    message_to_admin = "A new group named <a href=#{group_path(group)}>#{group.name}</a> is created.
     Please go to this <a href=#{requests_path}>link</a> to approve it."
    admin = Admin.first

    Notification.send_notification(admin, 'New Group Created', message_to_admin)
    Notification.send_notification(group.group_leader, 'New Group Created', message_to_group_leader)
  end

  def group_new_leader_notifications(group, user)
    message_to_group_leader = "You have successfully requested <a href=#{user_path(user)}>#{user.name}</a>
       to lead group named <a href=#{group_path(group)}>#{group.name}</a>."
    message_to_user = "<a href=#{user_path(group.group_leader)}>#{group.group_leader.name.capitalize}</a>
      has requested you to lead group named <a href=#{group_path(group)}>#{group.name}</a>.
      Please go to this <a href=#{requests_path}>link</a> to approve it."
    Notification.send_notification(user, 'New Group Leader Request', message_to_user)
    Notification.send_notification(group.group_leader, 'New Group Leader Request', message_to_group_leader)
  end

  def add_members_notification_to_user(group, user)
    message = "You have been added to group named <a href=#{group_path(group)}>#{group.name}</a>."
    Notification.send_notification(user, 'Added to Group', message)
  end

  def remove_members_notification_to_user(group, user)
    message = "You have been removed from group named <a href=#{group_path(group)}>#{group.name}</a>."
    Notification.send_notification(user, 'Removed from Group', message)
  end

  def leave_notification(group, user)
    message_to_user = "You have left group named <a href=#{group_path(group)}>#{group.name}</a>."
    message_to_group_leader = " <a href=#{user_path(current_user)}>#{current_user.name.capitalize}</a> has left group named <a href=#{group_path(group)}>#{group.name}</a>."

    Notification.send_notification(user, 'Left from Group', message_to_user)
    Notification.send_notification(group.group_leader, 'Left from Group', message_to_group_leader)
  end

end

app/views/groups/_group.html.slim
.col-sm-6.col-md-4
  .group-index-item onclick="location.href='#{group_path(group)}';"
    .row
      .col-xs-4.col-sm-4.col-md-3
        = image_tag group.avatar.url(:thumb), :class => 'avatar search-group-image'
      .col-xs-8.col-sm-8.col-md-9
        h3 
          = group.name.capitalize
      .col-xs-12.m-t-30
        .row
          .col-xs-4
            .font-weight-500
              | Group Leader:   
          .col-xs-8
              | #{group.group_leader.name}
        .row
          .col-xs-4
            | Group Location: 
          .col-xs-8
            = group.location 
        .row
          .col-xs-4
            | Affiliations:
          .col-xs-8
            - if !group.projects.blank?
              - projects = ''
              - group.projects.each do |project|
                - projects += "#{project.name},"
              = projects.chop.truncate(30)
            - else 
              = "Not affiliated to any projects yet."
        .row
          .col-xs-4
            | No. of Members
          .col-xs-8
            = group.users.size
            |  member(s) 
        .group-index-join-btn.text-center
          - if can? :transfer_leadership, group
            = button_to "Manage", manage_group_path(group), :method => 'get', :class => 'group-index-mng-button'
          - elsif can? :leave, group
            = button_to "Leave Group", leave_group_path(group), data: {confirm: "Are you sure you want to leave #{group.name}?"}, :method => 'put', :class => 'group-index-mng-button'
          - else
            = button_to "Join Group", join_group_path(group.id), :method => 'put', :class => 'group-index-mng-button'

app/views/groups/_management.html.slim
/!
	#nav
	  =link_to "Edit Group", edit_group_path(@group), :method => 'get'
	  br
	  =link_to "Manage Members", manage_group_path(@group), :method => 'get'
	  br
	  =link_to "Transfer Leadership", transfer_group_leadership_path(@group), :method => 'get'
	  br
	  =link_to "Done", group_path(@group), :method => 'get'
	  br



.list-group        

  - if current_page?(action: "edit") && !params["id"].nil?
    a.selected-tab
      | Edit Group
  - else   
    a.list-group-item href=edit_group_path
      | Edit Group

  - if (current_page?(action: "manage_members") && !params["id"].nil?) || (current_page?(action: "pick_members") && !params["id"].nil?) || (current_page?(action: "remove_members") && !params["id"].nil?)
    a.selected-tab
      | Manage Members
  - else   
    a.list-group-item href=manage_group_path
      | Manage Members

  - if current_page?(action: "transfer_leadership") && !params["id"].nil?
    a.selected-tab
      | Transfer Leadership
  - else   
    a.list-group-item href=transfer_group_leadership_path
      | Transfer Leadership


  a.list-group-item href=group_path(@group)
    | Done


app/views/groups/index.html.slim
/!
  p#notice
    = notice
  h1
    | Explore
  table
    - @groups.each do |group|
      tr
        td
          =link_to group.name, group_path(group)
          br
          |  Group Leader: 
          =group.group_leader.name
          br
          |  Location: 
          =group.location
          br
          |  Affiliations: 
          - group.projects.each do |project|
            =project.name
          br
          =group.users.size
          |  member(s) 
          - if can? :transfer_leadership, group
            =button_to "Manage", manage_group_path(group), :method => 'get', :class => 'mng-button'
          - elsif can? :leave, group
            =button_to "Leave Group", leave_group_path(group), data: {confirm: "Are you sure you want to leave this group?"}, :method => 'put', :class => 'mng-button'
          - else
            =button_to "Join Group", join_group_path(group.id), :method => 'put', :class => 'mng-button'


.row.p-l-90
  h2
    = "Your Groups"
.row.m-60
  - if @groups.empty?
    .row.text-center
      i
        = "You are not associated with any groups."
  - else
    #groups-index
      = render @groups
#paginator.paginator.paginator-xs
  = paginate @groups,:window => 1,:remote => true          

app/views/groups/index.js.erb
$('#groups-index').html('<%= escape_javascript render(@groups) %>');

$('#paginator').html('<%= escape_javascript(paginate(@groups, :remote => true).to_s) %>');

app/views/groups/manage_members.html.slim
/!
  =render partial: 'management'
  #section
    h1
      | Manage Group
    |  Members: 
    br
    ol
      - @members.each do |member|
        li
          =link_to member.name, user_path(member)
    =button_to "Add New Members", pick_group_members_path(@group), :method => 'get'
    =button_to "Remove Members", remove_group_members_path(@group), :method => 'get'
    br
    |  Pending Requests: 
    br
    - if @requests.empty?
      i
        | There are no pending requests for 
        =@group.name
    - else
      ol
        - @requests.each do |request|
          li
            =link_to request.user.name, user_path(request.user)
            = button_to "Approve", approve_request_path(request), :method => 'put'
            = button_to "Decline", decline_request_path(request), :method => 'put'


div.edit-profile-page
  .row
    .col-md-3
      = render partial: 'management'
    .col-md-offset-1.col-md-4
      .form-elements
        h1
          Manage Members
          br
          small Current Members
        br
        ol
          - @members.each do |member|
            li
              =link_to member.name, user_path(member)

        h1
          |  Pending Requests: 
        br
        - if @requests.empty?
          i
            | There are no pending requests for 
          =@group.name
        - else
          ol
            - @requests.each do |request|
              li
                = link_to request.user.name, user_path(request.user)
                = button_to "Approve", approve_request_path(request), :method => 'put', :class => 'button transfer-leadership-button m-b-10'
                = button_to "Decline", decline_request_path(request), :method => 'put', :class => 'button transfer-leadership-button'

        
    .col-md-4
        =button_to "Add Users", pick_group_members_path(@group), :method => 'get', :class => 'button transfer-leadership-button m-b-20'
        =button_to "Remove Users", remove_group_members_path(@group), :method => 'get', :class => 'button transfer-leadership-button'


          

app/views/groups/show.html.slim
/!
  h1
    | Key Screen 6: Group Page
  table[width="100%"]
    tr
      td[width="25%"]
        = image_tag @group.avatar.url(:thumb), :class => 'avatar'
      td[width="25%"]
        =@group.name
        br
        =@members.size
        |  member(s)
        br
        |  Scale: 
        =@group.scale
        br
        |  Location: 
        =@group.location
        br
      td[width="25%"]
        |  Contact: 
        br
        =link_to @group.group_leader.name, user_path(@group.group_leader)
        |  / Project Manager 
        br
        =@group.group_leader.email
        |  / 
        =@group.group_leader.mobile
        br
      td[width="25%"]
        - if can? :transfer_leadership, @group
          =button_to "Manage Group", manage_group_path(@group), :method => 'get'
        - elsif can? :leave, @group
          =button_to "Leave Group", leave_group_path(@group), data: {confirm: "Are you sure you want to leave #{@group.name}?"}, :method => 'put'
        - else
          - if @join_request_Sent
            =button_to "Request Sent", #, disabled: disabled
          - else
            =button_to "Join Group", join_group_path(@group), :method => 'put'
  hr
  table[width="100%"]
    tr
      td[width="25%"]
        - if can? :transfer_leadership, @group
          =button_to "Add Members", add_group_members_path(@group)

        |  Members: 
        br
        - @members.each do |member|
          =link_to member.name, user_path(member)
          br
      td[width="50%"]
        |  Posts: 
        br
        - if @posts.empty?
          i
            =@group.name
            |  has no posts
          =render partial: 'posts/new'
        - else
          table.inbox[width="80%" border="1"]
            - @posts.each do |post|
              tr
                td
                  =link_to post.poster.name, user_path(post.poster)
                  | : 
                  =post.body
                  br
                  =post.posted
            tr
              td
                = render partial: 'posts/new'
      td[width="25%"]
        |  Affiliated Projects: 
        br
        - if @projects.empty?
          i
            =@group.name
            |  is not affiliated with any projects
        - else
          - @projects.each do |project|
            =link_to project.name, project_path(:project_id => project, :conversation_id => project.conversations.first)































.row
  .col-md-2.col-sm-4
    .project-img
      = image_tag @group.avatar.url(:medium), class: 'group-img-width group-img-lg'


  .col-md-6.col-sm-8.col-xs-12
    .row.p-l-15-percentage
      .col-md-offset-2.col-sm-6.col-md-5.col-xs-6
        h3.text-muted.project-name
          b.no-wrap
            = @group.name
      .col-sm-6.col-md-5.col-xs-6
        h4.text-muted.m-t-20
          = "#{@members.size} Members"
      .row
      .col-md-offset-2.col-md-4.col-sm-6
        .row
          .col-md-6.col-sm-6.col-xs-6
            h4.text-muted Type
          .col-md-6.col-sm-6.col-xs-6
            h4  Type
        .row
          .col-md-6.col-sm-6.col-xs-6
            h4.text-muted Location
          .col-md-6.col-sm-6.col-xs-6
            h4 
              = @group.location
        .row
          .col-md-6.col-sm-6.col-xs-6
            h4.text-muted Scale
          .col-md-6.col-sm-6.col-xs-6
            h4 
              = @group.scale
      .col-md-offset-1.col-md-5.col-sm-6
        .row
          .col-md-4.col-sm-4.col-xs-6
            h4.text-muted Contact
          .col-md-8.col-sm-8
            h4.no-wrap.col-xs-6.p-l-0
              = @group.group_leader_name
        .row
          .col-md-4.col-sm-4.col-xs-6
          .col-md-8.col-sm-8.col-xs-6
            h4 
              = @group.group_leader_email
        .row
          .col-md-4.col-sm-4.col-xs-6
          .col-md-8.col-sm-8.col-xs-6
            h4 
              = @group.group_leader_mobile

  .col-md-4.col-sm-12.col-xs-12
    .col-md-12.col-sm-6.col-xs-12
      .groups-map
        iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA1SW3MPMF_i009FmEMzNfCj2NPhUk0Ixc&q=#{@group.location}"

    .col-md-12.col-sm-3.col-xs-12
      - if current_user.is_admin?
        - if @group.is_active?
          = button_to "Disable", update_group_status_path(@group), :method => 'put', :class => 'manage-group-btn'
        - else
          = button_to "Enable", update_group_status_path(@group), :method => 'put', :class => 'manage-group-btn'

      - else

        - if can? :transfer_leadership, @group
          =button_to "Manage", manage_group_path(@group), :method => 'get', :class => 'manage-group-btn'
        - elsif can? :leave, @group
          =button_to "Leave Group", leave_group_path(@group), data: {confirm: "Are you sure you want to leave #{@group.name}?"}, :method => 'put', :class => 'manage-group-btn'
        - else
          - if @join_request_sent
            =button_to "Request Sent", '#', :class => 'manage-group-btn btn', disabled: 'disabled'
          - else
            =button_to "Join Group", join_group_path(@group), :method => 'put', :class => 'manage-group-btn'
  
.row
  .col-md-12
    hr.group-silver-border
  
div.group-details-block.group-details-block-xs
  .row
    .col-md-8
      .row
        .col-xs-9.col-sm-10
          h3.text-muted.group-projects-list Projects

        .col-xs-3.col-sm-2
          - if !@group.projects.blank?
            p
              = link_to "See All", associated_projects_path(@group), :class => "project-members-see-all"
      .row
        - if @projects.empty?
          .row.text-center
            i
              =@group.name
              |  is not affiliated with any projects

        - else
          - @projects.each do |project| 
            .col-md-6.col-lg-6
              .well.well-modified
                .group-project-block
                  a href=project_path(project)
                    .row
                      .col-sm-4.col-xs-6.col-lg-5
                        .decendent-well-active
                          = image_tag project.avatar.url(:thumb)
                      .col-md-6.col-lg-7
                        h5.text-primary.heading-styles 
                          = "@#{project.code}"
                        br/
                        h5.heading-styles 
                          = project.name
                    .row    
                      .col-xs-4
                        h5.heading-styles Type
                      .col-xs-8
                        h5.heading-styles 
                          = "project type"
                    .row
                      .col-xs-4
                        h5.heading-styles Location
                      .col-xs-8
                        h5.heading-styles 
                          = project.location
                    .row
                      .col-xs-4
                        h5.heading-styles Scale
                      .col-xs-8
                        h5.heading-styles 
                          = project.scale
                    .row
                      .col-md-12
                        h4
                          small
                            | Description text goes here Nullam Cursus jthk lectus tristique pretium laoreet. Nullam Cursus
                            | lectus tristique pretium laoreet jjrll oal ppol...

    .col-md-4.col-sm-12.col-xs-12.p-r-0
      .row
        .col-md-offset.col-md-4.col-sm-4.col-xs-4 
          h3.text-muted.project-members-header  Members
        .col-md-offset-2.col-md-4.col-sm-8.col-xs-8
          .col-sm-6.col-md-12.col-xs-6
          - if can? :transfer_leadership, @group
            =button_to "Add +", pick_group_members_path(@group), :method => 'get', :class => 'add-button'
          .col-xs-6.col-sm-6.col-md-12.m-t-25
            p
              = link_to "See All", all_members_path(@group), :class => "project-members-see-all"

      .col-md-12.p-r-0
        .row
          .col-md-12
            hr.project-member-border

        .row.m-t-minus-30
          - @members.each do |member|
            .participants-list.col-xs-12.col-sm-6.col-md-12.m-t-30.m-0.p-0
              .col-xs-3.col-sm-3.col-md-4.p-0
                .div-rounded
              .col-xs-9.col-sm-9.col-md-8.p-l-10-percentage
                h4.project-members-name
                  b.no-wrap
                    = link_to member.name, user_path(member)
                h4.heading-styles.silver-color  
                  = member.location

