config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations"}

  
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'forgot_password'
      put 'forgot_password_send_otp'
      put 'forgot_password_process_otp'
      get 'forgot_password_enter_otp/:mobile' => 'users#forgot_password_enter_otp', as: 'forgot_password_enter_otp'
      get 'mass_signup' => 'users#mass_signup', as: 'mass_signup'
      post 'mass_create' => 'users#mass_create', as: 'mass_create'

    end
  end


  resources :conversations
  resources :messages
  resources :projects, only: [:index]
  resources :groups
  resources :requests
  resources :notifications, only: [:index]
  

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all




  root 'welcome#index'

  get 'home' => 'ui#index'

  post 'incoming' => 'api#receive'

  get 'projects/:id/edit' => 'projects#edit', as: 'edit_project'
  get 'projects/:id/list_of_users' => 'projects#list_of_users', as: 'all_participants'
  get 'projects/new' => 'projects#new', as: 'new_project'
  post 'projects' => 'projects#create'

  get 'welcome/home' => 'welcome#home', as: 'welcome'
  get 'groups/home' => 'groups#index'
  get 'groups/new' => 'groups#new'
  get 'groups/:id/list_of_users' => 'groups#list_of_users', as: 'all_members'
  get 'groups/:id/associated_projects' => 'groups#associated_projects', as: 'associated_projects'
  put 'projects/:id/join' => 'projects#join', as: 'join'
  put 'projects/:id/leave' => 'projects#leave', as: 'leave'
  get 'projects/:id/conversations/new' => 'conversations#new', as: 'new_convo'
  post 'projects/:id/conversations/' => 'conversations#create', as: 'create_new_convo'
  get  'projects/:id/conversations/:id' => 'conversations#show', as: 'view_convo'
  get  'projects/:id/conversations/:id/pick_users' => 'conversations#pick_users', as: 'pick_convo_users'
  put  'projects/:id/conversations/:id/add_users/' => 'conversations#add_users', as: 'add_convo_users'

  get  'projects/:id/pick_users' => 'projects#pick_users', as: 'pick_project_users'
  put  'projects/:id/add_users/' => 'projects#add_users', as: 'add_project_users'

  get 'projects/:id/dashboard' => 'projects#dashboard'
  get 'dashboard/messages' => 'dashboard#messages'
  get 'dashboard/equity' => 'dashboard#equity'
  get 'dashboard/cloud' => 'dashboard#cloud'

  post 'messages/create' => 'messages#create', as: 'post_new_message'
  get 'projects/:project_id/show' => 'projects#show', as: 'project'
  patch 'projects/:id' => 'projects#update', as: 'update_project'


  get 'users/:id/manage' => 'users#manage', as: 'manage_user'
  get 'users/:id/delete_account' => 'users#delete_account', as: 'delete_account'
  patch 'users/:id/delete_user' => 'users#delete_user', as: 'delete_user'
  


  get 'projects/:id/manage' => 'projects#manage_participants', as: 'manage_project'
  get 'projects/:id/remove_participants' => 'projects#remove_participants', as: 'remove_project_participants'
  put 'projects/:id/remove' => 'projects#remove_participant', as: 'remove_project_participant'
  get 'projects/:id/transfer_leadership' => 'projects#transfer_leadership', as: 'transfer_project_leadership'
  post 'projects/:id/new_leader' => 'projects#new_leader', as: 'new_leader'

  put 'requests/:id/approve' => 'requests#approve', as: 'approve_request'
  put 'requests/:id/decline' => 'requests#decline', as: 'decline_request'
  put 'requests/:id/cancel_request' => 'requests#cancel_request', as: 'cancel_request'
  
  get 'projects/:id/add_affiliations' => 'projects#add_affiliations', as: 'add_affiliations'
  put 'projects/:id/affiliate' => 'projects#affiliate', as: 'affiliate'

  put 'users/:id/add_contact' => 'users#add_colleague', as: 'add_contact'
  put 'users/:id/remove_contact' => 'users#remove_colleague', as: 'remove_contact'
  

  put 'groups/:id/join' => 'groups#join', as: 'join_group'
  put 'groups/:id/leave' => 'groups#leave', as: 'leave_group'

  get 'groups/:id/manage' => 'groups#manage_members', as: 'manage_group'

  get  'groups/:id/pick_members' => 'groups#pick_members', as: 'pick_group_members'
  put  'groups/:id/add_members/' => 'groups#add_members', as: 'add_group_members'
  get 'groups/:id/remove_members' => 'groups#remove_members', as: 'remove_group_members'
  put 'groups/:id/remove_member' => 'groups#remove_member', as: 'remove_group_member'
  get 'groups/:id/transfer_leadership' => 'groups#transfer_leadership', as: 'transfer_group_leadership'
  post 'groups/:id/new_leader' => 'groups#new_leader', as: 'new_group_leader'

  get 'conversations/:id/posts/new' => 'posts#create', as: 'new_post'
  post 'conversations/:id/posts' => 'posts#create', as: 'create_post'

  get 'projects/:id/change_plan' => 'projects#change_plan', as: 'change_project_plan'
  

  get 'search' => 'search#index', :as => 'search'
  get 'search/contacts' => 'search#contacts', :as => 'contacts_results'
  get 'search/projects' => 'search#projects', :as => 'projects_results'
  get 'search/groups' => 'search#groups', :as => 'groups_results'


  put 'admin/:id/change_user_status' => 'admin#change_user_status', :as => 'update_user_status' 
  put 'admin/:id/change_project_status' => 'admin#change_project_status', :as => 'update_project_status' 
  put 'admin/:id/change_group_status' => 'admin#change_group_status', :as => 'update_group_status' 

  get 'welcome/contact_us' => 'welcome#contact_us', :as => 'contact_us'
  get 'welcome/about_us' => 'welcome#about_us', :as => 'about_us'
  get 'welcome/plan' => 'welcome#plan', :as => 'plan'
  post 'welcome/send_authentication_code' => 'welcome#send_authentication_code', :as => 'send_authentication_code'
  post 'welcome/authenticate_code' => 'welcome#authenticate_code', :as => 'authenticate_code'
  
  put 'notifications/mark_as_read' => 'notifications#mark_as_read', :as => 'mark_as_read'
  put 'notifications/mark_all_as_read' => 'notifications#mark_all_as_read', :as => 'mark_all_as_read'
  


  resources :passwords do
    collection do
      put 'change_password', as: :change
    end
  end









end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if current_user
      redirect_to '/home' and return
    end
    @user = User.new
  end

  def home
    @user = current_user
    @projects = @user.projects
    @conversations = @user.conversations
    @groups = @user.groups
    @messages = []
    @conversations.each do |conversation|
      @messages += conversation.messages
    end
    @messages.each do |message|
      message.mark_as_read! :for => current_user
    end

    @lead_project_requests = LeadProject.where(:user_id => @user.id, :pending => true)
    @lead_group_requests = LeadGroup.where(:user_id => @user.id, :pending => true)
  end

  def search
    @results = []
    #if params[:search]
    @search_key = params[:search]
    @users = User.search(@search_key)#.order("created_at DESC")
    @projects = Project.search(@search_key)#.order("created_at DESC")
    @groups = Group.search(@search_key)#.order("created_at DESC")
    #else
      #@posts = Post.all.order('created_at DESC')
    #end
  end

  # def notifications
  #   @user = current_user
  #   @lead_project_requests = LeadProject.where(:user_id => @user.id, :pending => true)
  #   @lead_group_requests = LeadGroup.where(:user_id => @user.id, :pending => true)
  #   @projects = Project.where(:project_manager_id => @user.id)
  #   @groups = Group.where(:group_leader_id => @user.id)
  #   @join_project_requests = []
  #   @projects.each do |project|
  #     @join_project_requests += project.requests.where(:type => 'JoinProject', :pending => true)
  #   end
  #   @join_group_requests = []
  #   @groups.each do |group|
  #     @join_group_requests += group.requests.where(:type => 'JoinGroup', :pending => true)
  #   end
  # end


  def contact_us
    @user = User.new
  end

  def about_us
  end

  def plan
  end

  def send_authentication_code
    country_code = params[:countryCode]
    phone_number = params[:phoneNumber]
    code = Faker::Number.hexadecimal(6)
    number = country_code+phone_number
    # number = 918686638646

    if phone_number.length == 10
      authentication_code = AuthenticationCode.create(phone_number: number, code: code)

      clickatell_response = Curl.get('http://api.clickatell.com/http/sendmsg', {
        :user => 'hihihihi',
        :password => 'FKXeNCeXfTcZfZ',
        # :api_id => user.country == 'USA' ? 3559754 : 3549952,
        :api_id => 3599889,
        # :from => user.country == 'USA' ? 12134585108 : 44760,
        :MO => 1,
        :to => number,
        :text => 'Hi your authentication code for clickatell is #{code}. Please enter this to continue.'
      })

      authentication_code.update(clickatell_message_id: clickatell_response.body)

      render :json => {
        :status => 'success'
      }
    else
      render :json => {
        :status => 'failure',
        :message => 'Please enter a valid phone number.'
      }
    end


  end

  def authenticate_code
    country_code = params[:countryCode]
    phone_number = params[:phoneNumber]
    code = params[:code]
    number = country_code+phone_number
    # number = 918686638646

    authentication_code = AuthenticationCode.where(phone_number: number).last
    if authentication_code.code  == code
      render :json => {
        :status => 'success'
      }

    else
      render :json => {
        :status => 'failure',
        :message => 'Wrong code. Please try again.'
      }

    end
  end
end

app/views/welcome/_gmap.html.erb
<iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0"width="571" height="443" src="https://maps.google.com/maps?hl=en&q=421 Nash Drive, Charlottesville, Virginia&ie=UTF8&t=roadmap&z=15&iwloc=B&output=embed"><div><small><a href="http://embedgooglemaps.com">embedgooglemaps.com</a></small></div><div><small><a href="https://ww.premiumlinkgenerator.com/">premium link generator</a></small></div></iframe>

app/views/welcome/_header.html.slim
/!
  .row
    .col-md-12
      /! header
      nav.navbar.navbar-default.header-padding
        .container-fluid.header-background
          /! Brand and toggle get grouped for better mobile display
          .navbar-header
            a.logo href=home_path
              img alt="Hicomm Web" src=asset_path('logo.png') class="logo-style"
          /! Collect the nav links, forms, and other content for toggling
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            ul.nav.navbar-nav.navbar-right.header-items.p-l-40
              li
                a href="#"  ABOUT
              li
                a href="#"  PLAN
              li
                a href="#"  CONTACT US
              li
                a href="#"  LOGIN
          /! /.navbar-collapse
        /! /.container-fluid



nav.navbar.navbar-inverse.home-header role="navigation"
  .container-fluid
    /! add header
    .navbar-header
      button.navbar-toggle data-target="#navbar1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a href=root_path
        img alt="" src=asset_path('logo.png') class="logo-style logo"

    /! add menu
    #navbar1.collapse.navbar-collapse.search-box
      /!
        form.navbar-form.navbar-left role="search"
          .input-group
            input.form-control placeholder=("Search this site") type="text" /
            span.input-group-btn
              button.btn.btn-default type="submit"
                span.glyphicon.glyphicon-search
      ul.nav.navbar-nav.extra-header-links.p-l-40
        li
          a href=mass_signup_users_path  MASS SIGNUP
        li
          a href=about_us_path  ABOUT US
        li
          a href=plan_path  PLAN
        li
          = link_to('CONTACT US', contact_us_path, 'data-no-turbolink' => true)
        

app/views/welcome/_logo.html.erb
<div id="header_image">
     <img src="logo.png" width="180" height="48" />
</div> 

app/views/welcome/about_us.html.slim
/!
	h1
		= "About Us"

app/views/welcome/contact_us.html.slim
.text-center
	h1
		= "Contact Us"
	.b-b-2.m-h-20
	.m-30
	h3
		= "We'd love"
		= " to help"
	h5
		= "If you are interested in using HiComm, please drop us a line!"

	.row
		.col-md-offset-2.col-md-4
			.contact-form
				.form-elements
					input.form-control placeholder=("Your Name") type="text" 
					input.form-control placeholder=("Email") type="text" 
					textarea.m-t-10.form-control placeholder=("Message") rows=8
        	button.button-format.m-t-30	Submit

		.col-md-offset-1.col-md-4
			.contact-details.m-t-10		
				span.glyphicon.glyphicon-earphone.grey-color.pull-left.p-l-10-percentage 
		    p
		    | 5037806755
		    br.m-t-10
		    span.glyphicon.glyphicon-envelope.font-14.grey-color.pull-left.p-l-10-percentage 
		    | vse7fd@virginia.edu
		   	
	    	#contact-us-map.m-t-10




app/views/welcome/home.html.slim
h1
  | Key Screen 2 - Main Page
br
- if !@lead_project_requests.empty?
  |  Requests - You have been requested to lead the following projects 
  br
  - @lead_project_requests.each do |request|
    =request.project.name
    =button_to "Accept", approve_request_path(request), confirm: "Are you sure you want to assume leadership of #{project.name}?", :method => 'put'
    =button_to "Decline", decline_request_path(request), :method => 'put'
- if !@lead_group_requests.empty?
  |  Requests - You have been requested to lead the following groups 
  br
  - @lead_group_requests.each do |request|
    =request.group.name
    =button_to "Accept", approve_request_path(request), confirm: "are you sure you want to assume leadership of #{group.name}?", :method => 'put'
    =button_to "Decline", decline_request_path(request), :method => 'put'
br
hr
table[width="100%"]
  tr
    td[width="25%"]
      =button_to "New Project", new_project_path, :method => 'get'
      |  My Projects: 
      br
      - @projects.each do |project|
        =link_to project.name, project_path(:project_id => project, :conversation_id => project.conversations.first), :method => 'get'
        br
    td[width="50%"]
      |  Inbox:
      br
      table.inbox[border="1" width="80%"]
        - @conversations.each do |conversation|
          tr
            td
              =link_to conversation.name, project_path(:project_id => conversation.project, :conversation_id => conversation)
              br
              - if conversation.messages.empty?
                |  There are no messages in this conversation 
              - else
                =link_to conversation.messages.last.sender.name, user_path(conversation.messages.last.sender), :method => 'get'
                | : 
                = conversation.messages.last.body
                br
                =conversation.messages.last.sent
    td[width="25%"]
      =button_to "New Group", new_group_path, :method => 'get'
      |  My Groups: 
      br
      - @groups.each do |group|
        =link_to group.name, group_path(group), :method => 'get'
        br
      = button_to 'Explore', groups_path, :method => 'get'

app/views/welcome/index.html.slim
/!
	.row
		.col-md-6
		  .well
		    h2 HiComm's Mission.
		    p Our mission is to create an open, active, and collaborative network of communities, university groups, and service organizations in order to foster empowered and sustainable community partnerships that overcome development challenges.
		   	button.btn.btn-primary.left-block Learn More

		.col-md-6
		  .well
		    = render 'devise/sessions/new'
		  .well
		    = render 'devise/registrations/new'

	.row
		.col-md-6
		  .well
		   	h3 Plan
		   	p HiComm empowers both communities and service organizations to communicate and exchange information through an accessible, low-cost, and networkable platform. We do this by combining a powerful web application with an SMS interface and subsidizing the cost of SMS messages sent from the field. By overcoming the burdens and expenditures associated with community development logistics, HiComm can assist organizations and communities overcome logistical barriers and focus on the task at hand. We believe that an open, active, and collaborative network of communities, non-profits, and universities, primary stakeholders involved in community development projects, fosters, empowers, and sustains community partnerships. 
		   	<img src="<%= asset_path( 'plan.png' ) %>" />

	.row
		.col-md-6
		  .well
		   	h3 Contact Us



.row.m-t-94.m-5-percentage.text-center
  .col-md-6.col-xs-12.text-left
    /! body1
    h1#hicomm-mission
      small HiComm's Mission
    h3
      small.m-t-16
	    p 
	    | Our mission is to create an open, active, and collaborative network of communities, university groups, and service organizations 
	    | in order to foster empowered and sustainable community partnerships that overcome development challenges.

    /!
	    h1#team
	      small Team
	    h3
	      small.m-t-16

	/!
	    h1#plan
		  small Plan
	    h3
	      small.m-t-16
		   	| HiComm empowers both communities and service organizations to communicate and exchange information through an accessible, low-cost, and networkable platform. We 
		   	| do this by combining a powerful web application with an SMS interface and subsidizing the cost of SMS messages sent from the field. By overcoming the burdens 
		   	| and expenditures associated with community development logistics, HiComm can assist organizations and communities overcome logistical barriers and focus on the 
		   	| task at hand. We believe that an open, active, and collaborative network of communities, non-profits, and universities, primary stakeholders involved in 
		   	| community development projects, fosters, empowers, and sustains community partnerships. 
	    
    a href=about_us_path
    	button.button-format.m-t-30.m-b-20 Learn More


    /!
	    h1#contact-us
	      small Contact Us
	    h3
	      small.m-t-16
		    p 
		    | Contact Number: 5037806755
		    br
		    | Contact Mail: vse7fd@virginia.edu
		   	
	    #contact-us-map


  .col-md-6.col-xs-12.sign-in-sign-up-block.centre
  	= render 'devise/sessions/new'
  	= render 'devise/registrations/new'

app/views/welcome/notifications.html.slim
h1
  | Notifications
- if notification_count == 0
  |  You have no new notifications
- else
  - @lead_project_requests.each do |request|
    |  You have been requested to lead
    =request.project.name
    =button_to "Approve", approve_request_path(request), :method => 'put'
    =button_to "Decline", decline_request_path(request), :method => 'put'
  - @lead_group_requests.each do |request|
    |  You have been requested to lead
    =request.group.name
    =button_to "Approve", approve_request_path(request), :method => 'put'
    =button_to "Decline", decline_request_path(request), :method => 'put'
  - @join_project_requests.each do |request|
    =request.user.name
    |  has requested to join
    =request.project.name
    =button_to "Approve", approve_request_path(request), :method => 'put'
    =button_to "Decline", decline_request_path(request), :method => 'put'
  - @join_group_requests.each do |request|
    =request.user.name
    |  has requested to join
    =request.group.name
    =button_to "Approve", approve_request_path(request), :method => 'put'
    =button_to "Decline", decline_request_path(request), :method => 'put'

app/views/welcome/plan.html.slim
/!
	.m-30
		h1 Plan

		p
			| HiComm empowers both communities and service organizations to communicate and exchange information through an,
			| accessible, low-cost, and networkable platform. We do this by combining a powerful web application with an SMS
			| interface and subsidizing the cost of SMS messages sent from the field. By overcoming the burdens and
			| expenditures associated with community development logistics, HiComm can assist organizations and communities
			| overcome logistical barriers and focus on the task at hand. We believe that an open, active, and collaborative | network of communities, non-profits, and universities, primary stakeholders involved in community development
			| projects, fosters, empowers, and sustains community partnerships.

app/views/welcome/search.html.slim
/!
  h1
    | Search Page Key Screen 7
  |  Users (
  =@users.size
  | )
  br
  - if @users.present?
    - @users.each do |user|
      =link_to user.name, user_path(user)
      br
  - else
    p
      | There are no Users matching the term(s)
      = params[:search]
      | .
  |  Projects (
  =@projects.size
  | )
  br
  - if @projects.present?
    - @projects.each do |project|
      =link_to project.name, project_path(:project_id => project, :conversation_id => project.conversations.first)
      br
  - else
    p
      | There are no Projects matching the term(s)
      = params[:search]
      | .
  |  Groups (
  =@groups.size
  | )
  br
  - if @groups.present?
    - @groups.each do |group|
      =link_to group.name, group_path(group)
      br
  - else
    p
      | There are no Groups matching the term(s)
      = params[:search]
      | .


.search-page
  .row.p-l-40
    h3
      = "Search results for "
      b
        = " #{@search_key}"


  .search-contacts
    .row.p-l-55
      .col-sm-3
        h4
          = "Contacts (#{@users.count})"
      .col-sm-9.text-right
        h5
          a.search-see-all
            = "See all"
    .p-t-10
      - if @users.present?
        .p-l-13
          .row
            - @users.each do |user|
              .col-sm-4
                .search-contact onclick="location.href='#{user_path(user)}';"
                  .row
                    .col-sm-2
                      = image_tag user.avatar.url(:thumb), :class => 'avatar search-user-image'
                    .col-sm-10
                      .font-weight-900
                        = user.name
                      = user.job
      - else
        .p-l-40
          = "No results found"


  .search-projects
    .row.p-l-55
      .col-sm-3
        h4
          = "Projects (#{@projects.count})"
      .col-sm-9.text-right
        h5
          a.search-see-all
            = "See all"
    .p-t-10
      - if @projects.present?
        .p-l-13
          .row
            - @projects.each do |project|
              .col-sm-4
                .search-contact onclick="location.href='#{project_path(project)}';"
                  .row
                    .col-sm-2
                      = image_tag project.avatar.url(:thumb), :class => 'avatar search-project-image'
                    .col-sm-10
                      .font-weight-900
                        = project.name
                      = project.scale
                      br
                      = project.location
      - else
        .p-l-40
          = "No results found"

  .search-groups
    .row.p-l-55
      .col-sm-3
        h4
          = "Groups (#{@groups.count})"
      .col-sm-9.text-right
        h5
          a.search-see-all
            = "See all"

    .p-t-10
      - if @groups.present?
        .p-l-13
          .row
            - @groups.each do |group|
              .col-sm-4
                .search-contact onclick="location.href='#{group_path(group)}';"
                  .row
                    .col-sm-2
                      = image_tag group.avatar.url(:thumb), :class => 'avatar search-group-image'
                    .col-sm-10
                      .font-weight-900
                        = group.name
                      = group.scale
                      br
                      = group.location
      - else
        .p-l-40
          = "No results found"