config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations"}

  
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'forgot_password'
      put 'forgot_password_send_otp'
      put 'forgot_password_process_otp'
      get 'forgot_password_enter_otp/:mobile' => 'users#forgot_password_enter_otp', as: 'forgot_password_enter_otp'
      get 'mass_signup' => 'users#mass_signup', as: 'mass_signup'
      post 'mass_create' => 'users#mass_create', as: 'mass_create'

    end
  end


  resources :conversations
  resources :messages
  resources :projects, only: [:index]
  resources :groups
  resources :requests
  resources :notifications, only: [:index]
  

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all




  root 'welcome#index'

  get 'home' => 'ui#index'

  post 'incoming' => 'api#receive'

  get 'projects/:id/edit' => 'projects#edit', as: 'edit_project'
  get 'projects/:id/list_of_users' => 'projects#list_of_users', as: 'all_participants'
  get 'projects/new' => 'projects#new', as: 'new_project'
  post 'projects' => 'projects#create'

  get 'welcome/home' => 'welcome#home', as: 'welcome'
  get 'groups/home' => 'groups#index'
  get 'groups/new' => 'groups#new'
  get 'groups/:id/list_of_users' => 'groups#list_of_users', as: 'all_members'
  get 'groups/:id/associated_projects' => 'groups#associated_projects', as: 'associated_projects'
  put 'projects/:id/join' => 'projects#join', as: 'join'
  put 'projects/:id/leave' => 'projects#leave', as: 'leave'
  get 'projects/:id/conversations/new' => 'conversations#new', as: 'new_convo'
  post 'projects/:id/conversations/' => 'conversations#create', as: 'create_new_convo'
  get  'projects/:id/conversations/:id' => 'conversations#show', as: 'view_convo'
  get  'projects/:id/conversations/:id/pick_users' => 'conversations#pick_users', as: 'pick_convo_users'
  put  'projects/:id/conversations/:id/add_users/' => 'conversations#add_users', as: 'add_convo_users'

  get  'projects/:id/pick_users' => 'projects#pick_users', as: 'pick_project_users'
  put  'projects/:id/add_users/' => 'projects#add_users', as: 'add_project_users'

  get 'projects/:id/dashboard' => 'projects#dashboard'
  get 'dashboard/messages' => 'dashboard#messages'
  get 'dashboard/equity' => 'dashboard#equity'
  get 'dashboard/cloud' => 'dashboard#cloud'

  post 'messages/create' => 'messages#create', as: 'post_new_message'
  get 'projects/:project_id/show' => 'projects#show', as: 'project'
  patch 'projects/:id' => 'projects#update', as: 'update_project'


  get 'users/:id/manage' => 'users#manage', as: 'manage_user'
  get 'users/:id/delete_account' => 'users#delete_account', as: 'delete_account'
  patch 'users/:id/delete_user' => 'users#delete_user', as: 'delete_user'
  


  get 'projects/:id/manage' => 'projects#manage_participants', as: 'manage_project'
  get 'projects/:id/remove_participants' => 'projects#remove_participants', as: 'remove_project_participants'
  put 'projects/:id/remove' => 'projects#remove_participant', as: 'remove_project_participant'
  get 'projects/:id/transfer_leadership' => 'projects#transfer_leadership', as: 'transfer_project_leadership'
  post 'projects/:id/new_leader' => 'projects#new_leader', as: 'new_leader'

  put 'requests/:id/approve' => 'requests#approve', as: 'approve_request'
  put 'requests/:id/decline' => 'requests#decline', as: 'decline_request'
  put 'requests/:id/cancel_request' => 'requests#cancel_request', as: 'cancel_request'
  
  get 'projects/:id/add_affiliations' => 'projects#add_affiliations', as: 'add_affiliations'
  put 'projects/:id/affiliate' => 'projects#affiliate', as: 'affiliate'

  put 'users/:id/add_contact' => 'users#add_colleague', as: 'add_contact'
  put 'users/:id/remove_contact' => 'users#remove_colleague', as: 'remove_contact'
  

  put 'groups/:id/join' => 'groups#join', as: 'join_group'
  put 'groups/:id/leave' => 'groups#leave', as: 'leave_group'

  get 'groups/:id/manage' => 'groups#manage_members', as: 'manage_group'

  get  'groups/:id/pick_members' => 'groups#pick_members', as: 'pick_group_members'
  put  'groups/:id/add_members/' => 'groups#add_members', as: 'add_group_members'
  get 'groups/:id/remove_members' => 'groups#remove_members', as: 'remove_group_members'
  put 'groups/:id/remove_member' => 'groups#remove_member', as: 'remove_group_member'
  get 'groups/:id/transfer_leadership' => 'groups#transfer_leadership', as: 'transfer_group_leadership'
  post 'groups/:id/new_leader' => 'groups#new_leader', as: 'new_group_leader'

  get 'conversations/:id/posts/new' => 'posts#create', as: 'new_post'
  post 'conversations/:id/posts' => 'posts#create', as: 'create_post'

  get 'projects/:id/change_plan' => 'projects#change_plan', as: 'change_project_plan'
  

  get 'search' => 'search#index', :as => 'search'
  get 'search/contacts' => 'search#contacts', :as => 'contacts_results'
  get 'search/projects' => 'search#projects', :as => 'projects_results'
  get 'search/groups' => 'search#groups', :as => 'groups_results'


  put 'admin/:id/change_user_status' => 'admin#change_user_status', :as => 'update_user_status' 
  put 'admin/:id/change_project_status' => 'admin#change_project_status', :as => 'update_project_status' 
  put 'admin/:id/change_group_status' => 'admin#change_group_status', :as => 'update_group_status' 

  get 'welcome/contact_us' => 'welcome#contact_us', :as => 'contact_us'
  get 'welcome/about_us' => 'welcome#about_us', :as => 'about_us'
  get 'welcome/plan' => 'welcome#plan', :as => 'plan'
  post 'welcome/send_authentication_code' => 'welcome#send_authentication_code', :as => 'send_authentication_code'
  post 'welcome/authenticate_code' => 'welcome#authenticate_code', :as => 'authenticate_code'
  
  put 'notifications/mark_as_read' => 'notifications#mark_as_read', :as => 'mark_as_read'
  put 'notifications/mark_all_as_read' => 'notifications#mark_all_as_read', :as => 'mark_all_as_read'
  


  resources :passwords do
    collection do
      put 'change_password', as: :change
    end
  end









end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_filter :check_project_manager, except: [:index, :show, :new, :create, :join, :leave, :list_of_users]

  def index
  	@projects = current_user.projects.order(:name).page params[:page]
  end

	def show
		@user = current_user
		@project = Project.includes(:conversations, :users, :project_manager).friendly.find(params[:project_id])
		# if Project.paid.first.include? @project
			@conversations = @project.conversations.includes(:users)
			@participants = @project.users.limit(3)
			@project_manager = @project.project_manager
			if params[:conversation_id].nil?
				@current_convo = @project.conversations.first
			else
				@current_convo = Conversation.friendly.find(params[:conversation_id])
			end
			@messages = @current_convo.messages.includes(:sender)
	    @messages.each do |message|
	    	if message.sender != current_user
	 	  		message.mark_as_read! :for => current_user
 	  		end
    	end
	  	@conversation_users =  @current_convo.users

			@message = Message.new
  		@join_request_sent = !(JoinProject.pending.where(:request_by => current_user.id, :project_id => @project.id).blank?)

		# elsif Project.paid.last.include? @project
		# 	if current_user.managed_projects.include? @project
		# 		redirect_to home_path, :alert => "We still didn't get a payment confirmation of #{@project.name} from PayPal. So please come back after some time."
		# 	else
		# 		redirect_to home_path, :alert => 'You do not have access to this project'
		# 	end
		# elsif current_user.managed_projects.include? @project
		# 	redirect_to pay_path(@project), :alert => 'Please finish the payment to get into the project'
		# else
		# 	redirect_to home_path, :alert => 'You do not have access to this project'
		# end
	end

	def edit
		@project = Project.friendly.find(params[:id])
	end

	def update
		@project = Project.friendly.find(params[:id])
		@project.update_attributes(project_params)
		redirect_to :back, notice: "Your project information has been edited"
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.create(project_params.merge(:project_manager_id => current_user.id))
		if @project.save
			project_create_notifications(@project)
			redirect_to project_path(@project)
	    	# redirect_to pay_path(@project)
	    else
	      render :new
    end
		# redirect_to project_path(:project_id => @project, :conversation_id => @project.conversations.first)
	end

	def destroy
		@project = Project.friendly.find(params[:id])
		@project.destroy
	end

	def list_of_users
		@project = Project.includes(:users).friendly.find(params[:id])
		@users = @project.users
		@user_count = @users.size
	end

	def join
		@project = Project.friendly.find(params[:id])

		@request = Request.create(:project_id => @project.id, :user_id => current_user.id, :request_by => current_user.id,
			:request_to => @project.project_manager_id,:pending => true, :type => 'JoinProject')

		if @request.save!
			 project_join_request_notifications(@project)
		end
		redirect_to :back, notice: "Your request to join #{@project.name} has been sent"
	end

	def leave
		@project = Project.friendly.find(params[:id])
		@project.users.delete(current_user)
		leave_notification(@project, current_user)
		redirect_to :back
	end

	def pick_users
		@project = Project.friendly.find(params[:id])
		all_users = User.all
		existent_users = @project.users
		@users = all_users - existent_users
	end

	def add_users
		@project = Project.friendly.find(params[:project_id])
		@user = User.friendly.find(params[:user_id])
		@project.users << @user
		@project_wide_convo = @project.conversations.where(:name => "Project-Wide Conversation")
		@user.conversations << @project_wide_convo
		add_members_notification_to_user(@project, @user)
		redirect_to :back,  notice: "#{@user.name} was successfully added to #{@project.name}"
	end

	def manage_participants
		@project = Project.friendly.find(params[:id])
		@participants = @project.users
		@requests = JoinProject.where(:project_id => @project.id, :pending => true)
	end

	def remove_participants
		@project = Project.friendly.find(params[:id])
		@participants = @project.users - [@project.project_manager]
	end

	def remove_participant
		@project = Project.friendly.find(params[:project_id])
		@user = User.friendly.find(params[:user_id])
		@project.users.delete(@user)
		remove_members_notification_to_user(@project, @user)
		redirect_to :back, notice: "#{@user.name} was successfully removed from #{@project.name}"
	end

	def transfer_leadership
		@project = Project.friendly.find(params[:id])
		@participants = @project.users - [current_user]

		@requests_sent_by_user = LeadProject.pending.where(:request_by => current_user.id, :project_id => @project.id)
		@transfer_request_sent = !(@requests_sent_by_user.blank?)
		@transfer_leadership_to = User.find(@requests_sent_by_user.last.request_to) if @transfer_request_sent
	end

	def new_leader
		@project = Project.friendly.find(params[:project_id])
		@user = User.friendly.find(params[:user_id])
		@request = Request.create(:project_id => @project.id, :user_id => @user.id, :request_to => @user.id, :request_by => @project.project_manager_id, :pending => true, :type => 'LeadProject')
		redirect_to project_path(:project_id =>@project, :conversation_id => @project.conversations.first), notice: "leadership of #{@project.name} will be transfered to #{@user.name} upon approval"
	end

	def add_affiliations
		@project = Project.friendly.find(params[:id])
		@groups = Group.all - @project.groups
	end

	def affiliate
		@project = Project.includes(:groups).friendly.find(params[:project_id])
		@group = Group.friendly.find(params[:group_id])
		if @project.groups.size < 3
			@project.groups << @group
			redirect_to :back, notice: "#{@project.name} has been affiliated with #{@group.name}"
		else
			redirect_to :back, notice: "Sorry, #{@project.name} already has too many affiliations"
		end
	end

	def change_plan
		@project = Project.friendly.find(params[:id])
	end

	def dashboard
		@project = Project.friendly.find(params[:id])
		@total_messages_count = @project.messages.count
		@join_request_sent = !(JoinProject.pending.where(:request_by => current_user.id, :project_id => @project.id).blank?)
	end

	private

	def check_project_manager
		project = Project.friendly.find(params[:id])
		if current_user.managed_projects.include? project
			true
		else
			redirect_to project_path(project), notice: "Sorry, you cannot access this path."
		end
	end

	def project_params
		params.require(:project).permit(:name, :privacy, :plan, :location, :scale, :avatar)
	end

	def project_join_request_notifications(project)
		message_to_project_manager = "<a href=#{user_path(current_user)}>#{current_user.name.capitalize}</a> has requested
  		to join the project <a href=#{project_path(project)}>#{project.name}</a>. Please go to this <a href=#{requests_path}>link</a> to approve it."
		message_to_user = "Your request has been successfully placed to join the project <a href=#{project_path(project)}>#{project.name}</a>"

		Notification.send_notification(project.project_manager, 'Join Project', message_to_project_manager)
		Notification.send_notification(current_user, 'Join Project', message_to_user)
	end

	def project_create_notifications(project)
		message_to_project_manager = "You have successfully created a new project named <a href=#{project_path(project)}>#{project.name}</a>"
    message_to_admin = "A new project named <a href=#{project_path(project)}>#{project.name}</a> is created. Please go to this <a href=#{requests_path}>link</a> to approve it."
    admin = Admin.first

    Notification.send_notification(admin, 'New Project Created', message_to_admin)
		Notification.send_notification(project.project_manager, 'New Project Create', message_to_project_manager)
	end

  def project_new_leader_notifications(project, user)
    message_to_project_manager = "You have successfully requested <a href=#{user_path(user)}>#{user.name}</a>
       to lead project named <a href=#{project_path(project)}>#{project.name}</a>."
    message_to_user = "<a href=#{user_path(project.project_manager)}>#{project.project_manager.name.capitalize}</a>
      has requested you to lead project named <a href=#{project_path(project)}>#{project.name}</a>.
      Please go to this <a href=#{requests_path}>link</a> to approve it."

    Notification.send_notification(user, 'New Project Leader Request', message_to_user)
    Notification.send_notification(project.project_manager, 'New Project Leader Request', message_to_project_manager)
  end

  def add_members_notification_to_user(project, user)
  	message = "You have been added to project named <a href=#{project_path(project)}>#{project.name}</a>."
    Notification.send_notification(user, 'Added to Project', message)
  end

  def remove_members_notification_to_user(project, user)
  	message = "You have been removed from project named <a href=#{project_path(project)}>#{project.name}</a>."
    Notification.send_notification(user, 'Removed from Project', message)
  end


  def leave_notification(project, user)
    message_to_user = "You have left project named <a href=#{project_path(project)}>#{project.name}</a>."
    message_to_project_manager = " <a href=#{user_path(current_user)}>#{current_user.name.capitalize}</a> has left project named <a href=#{project_path(project)}>#{project.name}</a>."

    Notification.send_notification(user, 'Left from Project', message_to_user)
    Notification.send_notification(project.project_manager, 'Left from Project', message_to_project_manager)
  end

end

app/views/projects/_header.html.slim
.col-sm-6
  = image_tag @project.avatar.url(:thumb), :class => 'avatar'
.col-sm-6
  = "Project Name: #{@project.name}"
  br
  = "Size: #{@project.users.size} member(s)"
  br
  = "Location: #{@project.location}"
  br
  = "Scale: #{@project.scale}"
  br
  b = "Code: @#{@project.code}"
  br

app/views/projects/_management.html.slim
/!
  #nav
    =link_to "Edit Project", edit_project_path(:project_id => @project), :method => 'get'
    br
    =link_to "Change Plan", change_project_plan_path(@project), :method => 'get'
    br
    =link_to "Manage Participants", manage_project_path(@project), :method => 'get'
    br
    =link_to "Transfer Leadership", transfer_project_leadership_path(@project), :method => 'get'
    br
    =link_to "Add Affiliations", add_affiliations_path(@project), :method => 'get'
    br
    =link_to "Done", project_path(:project_id => @project, :conversation_id => @project.conversations.first), :method => 'get'
    br




.list-group        

  - if current_page?(action: "edit") && !params["id"].nil?
    a.selected-tab
      | Edit Project
  - else   
    a.list-group-item href=edit_project_path
      | Edit Project
  - if current_page?(action: "change_plan") && !params["id"].nil?
    a.selected-tab
      | Change Plan
  - else   
    a.list-group-item href=change_project_plan_path
      | Change Plan

  - if (current_page?(action: "manage_participants") && !params["id"].nil?) || (current_page?(action: "pick_users") && !params["id"].nil?) || (current_page?(action: "remove_participants") && !params["id"].nil?)
    a.selected-tab
      | Manage Participants
  - else   
    a.list-group-item href=manage_project_path
      | Manage Participants

  - if current_page?(action: "transfer_leadership") && !params["id"].nil?
    a.selected-tab
      | Transfer Leadership
  - else   
    a.list-group-item href=transfer_project_leadership_path
      | Transfer Leadership

  - if current_page?(action: "add_affiliations") && !params["id"].nil?
    a.selected-tab
      | Add Affiliations
  - else   
    a.list-group-item href=add_affiliations_path
      | Add Affiliations

  a.list-group-item href=project_path(@project)
    | Done


app/views/projects/dashboard.html.slim
.row
  .col-md-offset-1.col-md-2.col-sm-4
    .project-img
      = image_tag @project.avatar.url(:medium), class: 'project-img-width'


  .col-md-6.col-sm-8.col-xs-12
    .row.p-l-15-percentage
      .col-md-offset-2.col-sm-6.col-md-5.col-xs-6
        h3.text-muted.project-name
          b.no-wrap
            = @project.name
      .col-sm-6.col-md-5.col-xs-6
        h4.text-muted.m-t-20
          = "#{@project.users.count} Members"
      .row
      .col-md-offset-2.col-md-4.col-sm-6
        .row
          .col-md-6.col-sm-6.col-xs-6
            h4.text-muted Type
          .col-md-6.col-sm-6.col-xs-6
            h4  Type
        .row
          .col-md-6.col-sm-6.col-xs-6
            h4.text-muted Location
          .col-md-6.col-sm-6.col-xs-6
            h4 
              = @project.location
        .row
          .col-md-6.col-sm-6.col-xs-6
            h4.text-muted Scale
          .col-md-6.col-sm-6.col-xs-6
            h4 
              = @project.scale
      .col-md-offset-1.col-md-5.col-sm-6
        .row
          .col-md-4.col-sm-4.col-xs-6
            h4.text-muted Contact
          .col-md-8.col-sm-8
            h4.no-wrap.col-xs-6.p-l-0
              = @project.project_manager_name
        .row
          .col-md-4.col-sm-4.col-xs-6
          .col-md-8.col-sm-8.col-xs-6
            h4 
              = @project.project_manager_email
        .row
          .col-md-4.col-sm-4.col-xs-6
          .col-md-8.col-sm-8.col-xs-6
            h4 
              = @project.project_manager_mobile

  .col-md-3.col-sm-12.col-xs-12
    .col-md-12.col-sm-3.col-xs-6.pull-right
      - if current_user.is_admin?
        - if @project.is_active?
          = button_to "Disable", update_project_status_path(@project.id), :method => 'put', :class => 'go-to-dashboard-button'
        - else
          = button_to "Enable", update_project_status_path(@project.id), :method => 'put', :class => 'go-to-dashboard-button'

      - else

        - if can? :transfer_leadership, @project
          = button_to "Manage Project", manage_project_path(@project), :method => 'get', :class => 'go-to-dashboard-button'
        - elsif can? :leave, @project
          = button_to "Leave Project", leave_path(@project), data: { confirm: "Are you sure you want to leave #{@project.name}?"}, :method => 'put', :class => 'go-to-dashboard-button'
        - else
          - if @join_request_sent
            =button_to "Request Sent", '#', :class => 'go-to-dashboard-button btn', disabled: 'disabled'
          - else
            = button_to "Join Project", join_path(@project), :method => 'put', :class => 'go-to-dashboard-button'

.row.m-v-30
  .col-sm-12
    hr.project-details-bottom-border
div.project-details-block.project-details-block-xs 
  .row
    .col-md-4.col-sm-6.col-xs-12
      
      .col-md-7.col-sm-12.col-xs-8.m-b-10
        .dropdown#conversation data-conversation="all"
          button.btn.btn-default.dropdown-toggle data-toggle="dropdown" type="button"
            | All Conversations
            = " "
            span.caret
          ul.dropdown-menu.pointer
            li
              a#all All Conversations
            - @project.conversations.each do |conversation|
              li
                a id="#{conversation.id}" = conversation.name
      .col-md-5.col-sm-12.col-xs-4
        .dropdown.pointer.pull-left#time-range data-time="week"
          button.btn.btn-default.dropdown-toggle data-toggle="dropdown" type="button"
            | Last Week
            = " "
            span.caret
          ul.dropdown-menu
            li
              a#week Last Week
            li
              a#month Last Month
            li
              a#year Last Year
    .col-md-8.col-sm-6.col-xs-12
      .p-t-5.text-center
        .col-sm-12.col-md-4.col-xs-12
          .text-muted.font-weight-900
            = "Total Messages: #{@total_messages_count}"
        .col-sm-12.col-md-4.col-xs-12
          .text-muted.font-weight-900
            = "Total SMS: ###"
        .col-sm-12.col-md-4.col-xs-12
          .text-muted.font-weight-900
            = "Total FTEU: ###"

  
  .row.text-center#dashboard
    .col-md-4.col-sm-12.b-t-2.b-b-2.b-l-2.b-r-2.height-500 
      h3.p-t-40 Message by Time
      canvas#time.m-t-60
    .col-md-4.col-sm-12.b-t-2.b-b-2.b-l-2.b-r-2.height-500
      h3.p-t-40 Messaging Equity
      canvas#equity.m-t-60
      h3#equity-index.m-t-30
    .col-md-4.col-sm-12.height-500.b-l-2.b-r-2.b-b-2.b-t-2
      h3.p-t-40 Word cloud
      .word-cloud#cloud.m-t-60

app/views/projects/manage_members.html.erb
Manage Members <br />
Current Members<br />
<%@participants.each do |participant|%> 
	<%=participant.name%> <br />
<%end%>
Pending Requests: <br />
<%@requests.each do |request| %> 
	<%=request.user.name%> <%= button_to "Approve", approve_request_path(request), :method => 'put'%><%= button_to "Decline", decline_request_path(request), :method => 'put'%>
<%end%>
<br />
<%=button_to "Add Users", pick_project_users_path(@project), :method => 'get'%>
<%=button_to "Remove Users", remove_project_members_path(@project), :method => 'get'%>
<%=button_to "Transfer Leadership", transfer_project_leadership_path(@project), :method => 'get'%>
<%=button_to "Add Affiliations", add_affiliations_path(@project), :method => 'get' %>

app/views/projects/show.html.slim
.row
  .col-md-offset-1.col-md-2.col-sm-4
    .project-img
      = image_tag @project.avatar.url(:medium), class: 'project-img-width'


  .col-md-6.col-sm-8.col-xs-12
    .row.p-l-15-percentage
      .col-md-offset-2.col-sm-6.col-md-5.col-xs-6
        h3.text-muted.project-name
          b.no-wrap
            = @project.name
      .col-sm-6.col-md-5.col-xs-6
        h4.text-muted.m-t-20
          = "#{@participants.count} Members"
      .row
      .col-md-offset-2.col-md-4.col-sm-6
        .row
          .col-md-6.col-sm-6.col-xs-6
            h4.text-muted Type
          .col-md-6.col-sm-6.col-xs-6
            h4  Type
        .row
          .col-md-6.col-sm-6.col-xs-6
            h4.text-muted Location
          .col-md-6.col-sm-6.col-xs-6
            h4 
              = @project.location
        .row
          .col-md-6.col-sm-6.col-xs-6
            h4.text-muted Scale
          .col-md-6.col-sm-6.col-xs-6
            h4 
              = @project.scale
      .col-md-offset-1.col-md-5.col-sm-6
        .row
          .col-md-4.col-sm-4.col-xs-6
            h4.text-muted Contact
          .col-md-8.col-sm-8
            h4.no-wrap.col-xs-6
              = @project_manager.name
        .row
          .col-md-4.col-sm-4.col-xs-6
          .col-md-8.col-sm-8.col-xs-6
            h4 
              = @project_manager.email
        .row
          .col-md-4.col-sm-4.col-xs-6
          .col-md-8.col-sm-8.col-xs-6
            h4 
              = @project_manager.mobile

  .col-md-3.col-sm-12.col-xs-12
    .col-md-12.col-sm-3.col-xs-6
      - if current_user.is_admin?
        - if @project.is_active?
          = button_to "Disable", update_project_status_path(@project.id), :method => 'put', :class => 'go-to-dashboard-button'
        - else
          = button_to "Enable", update_project_status_path(@project.id), :method => 'put', :class => 'go-to-dashboard-button'

      - else
        - if can? :transfer_leadership, @project
          = button_to "Manage Project", manage_project_path(@project), :method => 'get', :class => 'go-to-dashboard-button'
        - elsif can? :leave, @project
          = button_to "Leave Project", leave_path(@project), data: { confirm: "Are you sure you want to leave #{@project.name}?"}, :method => 'put', :class => 'go-to-dashboard-button'
        - else
          - if @join_request_sent
            =button_to "Request Sent", '#', :class => 'go-to-dashboard-button btn', disabled: 'disabled'
          - else
            = button_to "Join Project", join_path(@project), :method => 'put', :class => 'go-to-dashboard-button'


    .col-md-12.col-sm-3.col-xs-6
      = button_to "Go to dashboard", "dashboard", :method => 'get', :class => 'go-to-dashboard-button'
    
.row.m-v-30
  .col-md-12
    hr.project-details-bottom-border
div.project-details-block.project-details-block-xs
  .row.project-details-block-1
    .col-md-3.col-sm-4.col-xs-12
      .row.text-center
        .f-24
          = "Message"
      .row.text-center
        /! = button_to "Project Message", new_convo_path(@project), :method => 'get', :class => 'add-conversation-button'
        - if can? :leave, @project  
          = button_to "New Conversation", new_convo_path(@project), :method => 'get', :class => 'add-conversation-button'

      .row
        .conversation-list.no-wrap.m-b-30
          - if @conversations.empty?
            p = "#{@project.name} has no conversations"
          - else
            - @conversations.each do |conversation|
              - if conversation == @current_convo
                = "\##{conversation.code}:#{conversation.name}"
              - else
                = link_to "\##{conversation.code}:#{conversation.name}", project_path(:project_id => @project, :conversation_id => conversation)
              br


    .col-md-6.col-sm-8.col-xs-12.p-0
      .conversation-detail
        = render partial: 'conversations/conversation', object: @current_convo


    .col-md-3.col-sm-12.col-xs-12.p-r-0
      .row
        .col-md-offset.col-md-4.col-sm-4.col-xs-4 
          h3.text-muted.project-members-header  Members
        .col-md-offset-2.col-md-4.col-sm-8.col-xs-8
          .col-sm-6.col-md-12.col-xs-6
            - if can? :add_users, @project
              = button_to "Add+", pick_project_users_path(@project), :method => 'get', :class => 'btn add-button'
          .col-xs-6.col-sm-6.col-md-12.m-t-25
            p
              = link_to "See All", all_participants_path(@project), :class => "project-members-see-all"
      .col-md-12.p-r-0
        .row
          .col-md-12
            hr.project-member-border

        .row.m-t-minus-30.m-b-30    
          - @participants.each do |participant|
            .participants-list.col-xs-12.col-sm-6.col-md-12.m-t-30.m-0.p-0
              .col-xs-3.col-sm-3.col-md-4.p-0
                .div-rounded
              .col-xs-9.col-sm-9.col-md-8.p-l-10-percentage
                h4.project-members-name
                  b.no-wrap
                    = link_to participant.name, user_path(participant)
                h4.heading-styles.silver-color  
                  = participant.location



